# Generated by Django 5.0.1 on 2025-06-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Currency code (e.g., USD, EUR)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Currency name (e.g., US Dollar)', max_length=100)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., $, €)', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this currency is available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
    ]
