# Generated by Django 5.0.1 on 2025-06-29 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_transaction', models.BooleanField(default=True)),
                ('email_budget', models.BooleanField(default=True)),
                ('email_reminder', models.BooleanField(default=True)),
                ('email_system', models.BooleanField(default=True)),
                ('email_achievement', models.BooleanField(default=True)),
                ('email_security', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_transaction', models.BooleanField(default=True)),
                ('push_budget', models.BooleanField(default=True)),
                ('push_reminder', models.BooleanField(default=True)),
                ('push_system', models.BooleanField(default=False)),
                ('push_achievement', models.BooleanField(default=True)),
                ('push_security', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('in_app_transaction', models.BooleanField(default=True)),
                ('in_app_budget', models.BooleanField(default=True)),
                ('in_app_reminder', models.BooleanField(default=True)),
                ('in_app_system', models.BooleanField(default=True)),
                ('in_app_achievement', models.BooleanField(default=True)),
                ('in_app_security', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(default='22:00')),
                ('quiet_hours_end', models.TimeField(default='08:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('transaction', 'Transaction'), ('budget', 'Budget'), ('reminder', 'Reminder'), ('system', 'System'), ('achievement', 'Achievement'), ('security', 'Security')], default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'type'], name='notificatio_user_id_827754_idx')],
            },
        ),
    ]
